/**
 * Shared inline styles for Quiz views
 */
export const quizStyles = {
  container: {
    maxWidth: '720px',
    margin: '0 auto',
    padding: '24px 16px',
    minHeight: '65vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: '24px',
    padding: '32px 28px',
    boxShadow: '0 10px 32px rgba(233, 30, 140, 0.1)',
    border: '1px solid #fce7f3',
  },
  idleBadge: {
    display: 'inline-block',
    padding: '4px 14px',
    borderRadius: '16px',
    backgroundColor: '#fff0f6',
    color: '#e91e8c',
    fontSize: '0.85rem',
    fontWeight: '700',
  },
  sectionBox: {
    backgroundColor: '#f8fafc',
    borderRadius: '18px',
    padding: '14px 18px',
    marginBottom: '14px',
    border: '1px solid #f1f5f9',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '10px',
    fontWeight: '700',
    color: '#334155',
    fontSize: '0.92rem',
  },
  selectInput: {
    padding: '4px 10px',
    borderRadius: '10px',
    border: '1.5px solid #e2e8f0',
    fontSize: '0.85rem',
    color: '#334155',
    outline: 'none',
    backgroundColor: '#ffffff',
    cursor: 'pointer',
  },
  dueSummaryBox: {
    backgroundColor: '#fffaf0',
    borderLeft: '4px solid #dd6b20',
    padding: '14px 18px',
    borderRadius: '12px',
    marginTop: '16px',
  },
  progressTrack: {
    width: '100%',
    height: '8px',
    backgroundColor: '#edf2f7',
    borderRadius: '4px',
    overflow: 'hidden',
    marginBottom: '16px',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#e91e8c',
    borderRadius: '4px',
    transition: 'width 0.3s ease',
  },
  metaRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  modeTag: {
    fontSize: '0.78rem',
    fontWeight: '700',
    backgroundColor: '#fff0f6',
    color: '#e91e8c',
    padding: '2px 8px',
    borderRadius: '10px',
  },
  questionPrompt: {
    backgroundColor: '#fffaf0',
    borderLeft: '4px solid #dd6b20',
    padding: '16px 20px',
    borderRadius: '12px',
    marginBottom: '24px',
  },
  promptSubLabel: {
    fontSize: '0.86rem',
    color: '#718096',
    display: 'block',
    marginBottom: '6px',
    fontWeight: '600',
  },
  promptMainText: {
    fontSize: '2rem',
    color: '#2d3748',
    margin: 0,
    fontWeight: '800',
    lineHeight: '1.3',
  },
  speakerMiniBtn: {
    padding: '4px 12px',
    backgroundColor: '#fff0f6',
    border: '1px solid #fbcfe8',
    borderRadius: '14px',
    color: '#e91e8c',
    fontSize: '0.82rem',
    fontWeight: '700',
    cursor: 'pointer',
    outline: 'none',
  },
  optionsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '14px',
  },
  replayAudioBtn: {
    position: 'absolute',
    right: '12px',
    top: '50%',
    transform: 'translateY(-50%)',
    backgroundColor: '#ffffff',
    border: '1.5px solid #e91e8c',
    color: '#e91e8c',
    borderRadius: '14px',
    padding: '4px 12px',
    fontSize: '0.78rem',
    cursor: 'pointer',
    fontWeight: '700',
    boxShadow: '0 2px 8px rgba(233, 30, 140, 0.2)',
    zIndex: 2,
  },
  scoreCircle: {
    width: '140px',
    height: '140px',
    borderRadius: '50%',
    border: '6px solid #fce7f3',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  wrongSectionBox: {
    backgroundColor: '#fff5f5',
    border: '1.5px solid #fed7d7',
    borderRadius: '18px',
    padding: '18px',
    marginBottom: '20px',
  },
  wrongGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
    gap: '10px',
    marginBottom: '16px',
  },
  wrongItemChip: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    padding: '10px 12px',
    border: '1px solid #feb2b2',
    textAlign: 'left',
  },
  retryMistakesBtn: {
    padding: '12px 24px',
    backgroundColor: '#e53e3e',
    color: '#ffffff',
    border: 'none',
    borderRadius: '25px',
    fontWeight: '700',
    fontSize: '0.95rem',
    boxShadow: '0 4px 14px rgba(229, 62, 62, 0.35)',
  },
  primaryBtn: {
    padding: '12px 28px',
    backgroundColor: '#e91e8c',
    color: '#ffffff',
    border: 'none',
    borderRadius: '25px',
    fontWeight: '700',
    fontSize: '0.95rem',
    boxShadow: '0 4px 14px rgba(233, 30, 140, 0.3)',
  },
  secondaryBtn: {
    padding: '12px 24px',
    backgroundColor: '#edf2f7',
    color: '#4a5568',
    border: 'none',
    borderRadius: '25px',
    fontWeight: '700',
    fontSize: '0.95rem',
  },
  outlineBtn: {
    padding: '12px 24px',
    backgroundColor: '#ffffff',
    color: '#e91e8c',
    border: '2px solid #e91e8c',
    borderRadius: '25px',
    fontWeight: '700',
    fontSize: '0.95rem',
  },
};
